//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DataObjects.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsSearchValue
    {
        public int Id { get; set; }
        public string ItemName { get; set; }
        public int CategoryID { get; set; }
        public string ItemName_Arabic { get; set; }
        public Nullable<bool> Expandable { get; set; }
    }
}
