//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DataObjects.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> OldAvailabilityStatus { get; set; }
        public Nullable<int> NewAvailabilityStatus { get; set; }
        public string Description { get; set; }
        public string StockKeeper { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int Quantity { get; set; }
    }
}
