//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DataObjects.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> OldAvailabilityStatus { get; set; }
        public Nullable<int> NewAvailabilityStatus { get; set; }
        public string Description { get; set; }
        public string StockKeeper { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<decimal> UnitAmount { get; set; }
        public int Quantity { get; set; }
        public string ToWhom { get; set; }
        public Nullable<bool> ShouldReturn { get; set; }
        public Nullable<int> ChildOfTransaction { get; set; }
        public string ItemName_Arabic { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> NewSchoolID { get; set; }
        public Nullable<int> ItemID { get; set; }
    
        public virtual AvailabilityStatu AvailabilityStatu { get; set; }
        public virtual AvailabilityStatu AvailabilityStatu1 { get; set; }
        public virtual Transaction Transaction1 { get; set; }
        public virtual Transaction Transaction2 { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual School School { get; set; }
        public virtual School School1 { get; set; }
    }
}
